### ISSUE TITLE
Non working lib?

### ISSUE THREAD

**Issue by reiven** [ranaroussi/pywallet#11]
Hi! 

I've tried install on virtualenv on OSX and Linux, via pip, but on both i got the same error importing the lib

```python
>>> from pywallet import wallet

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/pywallet/wallet.py", line 5, in <module>
    from .utils import (
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/pywallet/utils/__init__.py", line 5, in <module>
    from .ethereum import (
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/pywallet/utils/ethereum.py", line 19, in <module>
    from two1.bitcoin.utils import bytes_to_str
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/two1/bitcoin/__init__.py", line 19, in <module>
    from .block import BlockHeader
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/two1/bitcoin/block.py", line 7, in <module>
    from two1.bitcoin.txn import Transaction
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/two1/bitcoin/txn.py", line 7, in <module>
    from two1.bitcoin import crypto
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/two1/bitcoin/crypto.py", line 18, in <module>
    bitcoin_curve = secp256k1()
  File "/home/reiven/work/venv/wallet/local/lib/python2.7/site-packages/two1/crypto/ecdsa_openssl.py", line 449, in __init__
    super().__init__(hashlib.sha256)
TypeError: super() takes at least 1 argument (0 given)```

Thanks

**Comment by fenidik** [comment]
use python3 with pip3 install rlp==0.6.0

**Comment by henrytom1703** [comment]
@ranaroussi 
It's not working. I cannot install this library
```
(blockchain-env) tomtony@tomtony:~/python_env$ pip install pywallet
Collecting pywallet
Collecting two1>=3.10.8 (from pywallet)
  Using cached https://files.pythonhosted.org/packages/d4/d4/5f8e91bd0521568f4b2a0f0abecc273a632bc925320c6375ab2ab6290339/two1-3.10.9.tar.gz
Requirement already satisfied: six>=1.8.0 in ./blockchain-env/lib/python3.6/site-packages (from pywallet)
Requirement already satisfied: base58>=0.2.2 in ./blockchain-env/lib/python3.6/site-packages (from pywallet)
Requirement already satisfied: pycryptodome>=3.6.6 in ./blockchain-env/lib/python3.6/site-packages (from pywallet)
Requirement already satisfied: ecdsa>=0.11 in ./blockchain-env/lib/python3.6/site-packages (from pywallet)
Requirement already satisfied: arrow in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: click==6.6 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: docker-py==1.8.0 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: flake8 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: jsonrpcclient==2.0.1 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: jsonrpcserver==3.1.1 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: mnemonic==0.13 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: path.py in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Requirement already satisfied: pexpect in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Collecting protobuf==3.0.0a3 (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/d7/92/34c5810fa05e98082d141048110db97d2f98d318fa96f8202bf146ab79de/protobuf-3.0.0a3.tar.gz
Collecting pyaes (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/44/66/2c17bae31c906613795711fc78045c285048168919ace2220daa372c7d72/pyaes-1.6.1.tar.gz
Collecting pytest (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/57/94/305477fb977546970a3464c21b63c6800df6705384af2978b89acccfb151/pytest-3.10.1-py2.py3-none-any.whl
Collecting pyyaml (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz
Requirement already satisfied: requests<=2.11.1 in ./blockchain-env/lib/python3.6/site-packages (from two1>=3.10.8->pywallet)
Collecting sha256 (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/04/98/e2d70dc0af14a35ee62c5f6146120f8735e43e1de5daf633c61a2cdd8e67/sha256-0.1.tar.gz
Collecting tabulate (from two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/12/c2/11d6845db5edf1295bc08b2f488cf5937806586afe42936c3f34c097ebdc/tabulate-0.8.2.tar.gz
Requirement already satisfied: python-dateutil in ./blockchain-env/lib/python3.6/site-packages (from arrow->two1>=3.10.8->pywallet)
Requirement already satisfied: websocket-client>=0.32.0 in ./blockchain-env/lib/python3.6/site-packages (from docker-py==1.8.0->two1>=3.10.8->pywallet)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in ./blockchain-env/lib/python3.6/site-packages (from flake8->two1>=3.10.8->pywallet)
Requirement already satisfied: pycodestyle<2.5.0,>=2.4.0 in ./blockchain-env/lib/python3.6/site-packages (from flake8->two1>=3.10.8->pywallet)
Requirement already satisfied: setuptools>=30 in ./blockchain-env/lib/python3.6/site-packages (from flake8->two1>=3.10.8->pywallet)
Requirement already satisfied: pyflakes<2.1.0,>=2.0.0 in ./blockchain-env/lib/python3.6/site-packages (from flake8->two1>=3.10.8->pywallet)
Requirement already satisfied: future in ./blockchain-env/lib/python3.6/site-packages (from jsonrpcclient==2.0.1->two1>=3.10.8->pywallet)
Requirement already satisfied: jsonschema in ./blockchain-env/lib/python3.6/site-packages (from jsonrpcclient==2.0.1->two1>=3.10.8->pywallet)
Requirement already satisfied: funcsigs in ./blockchain-env/lib/python3.6/site-packages (from jsonrpcserver==3.1.1->two1>=3.10.8->pywallet)
Requirement already satisfied: pbkdf2 in ./blockchain-env/lib/python3.6/site-packages (from mnemonic==0.13->two1>=3.10.8->pywallet)
Requirement already satisfied: importlib-metadata>=0.5 in ./blockchain-env/lib/python3.6/site-packages (from path.py->two1>=3.10.8->pywallet)
Requirement already satisfied: ptyprocess>=0.5 in ./blockchain-env/lib/python3.6/site-packages (from pexpect->two1>=3.10.8->pywallet)
Collecting atomicwrites>=1.0 (from pytest->two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/3a/9a/9d878f8d885706e2530402de6417141129a943802c084238914fa6798d97/atomicwrites-1.2.1-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest->two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/3e/c7/3da685ef117d42ac8d71af525208759742dd235f8094221fdaafcd3dba8f/py-1.7.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest->two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/79/b1/eace304ef66bd7d3d8b2f78cc374b73ca03bc53664d78151e9df3b3996cc/more_itertools-4.3.0-py3-none-any.whl
Collecting pluggy>=0.7 (from pytest->two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/1c/e7/017c262070af41fe251401cb0d0e1b7c38f656da634cd0c15604f1f30864/pluggy-0.8.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest->two1>=3.10.8->pywallet)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Building wheels for collected packages: two1, protobuf, pyaes, pyyaml, sha256, tabulate
  Running setup.py bdist_wheel for two1 ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/two1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp2pj7xckmpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for two1
  Running setup.py clean for two1
  Running setup.py bdist_wheel for protobuf ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/protobuf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpxw8v690fpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for protobuf
  Running setup.py clean for protobuf
  Running setup.py bdist_wheel for pyaes ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/pyaes/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpdwiiot99pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyaes
  Running setup.py clean for pyaes
  Running setup.py bdist_wheel for pyyaml ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/pyyaml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbafn55hkpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
  Running setup.py bdist_wheel for sha256 ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/sha256/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpns593tu0pip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for sha256
  Running setup.py clean for sha256
  Running setup.py bdist_wheel for tabulate ... error
  Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/tabulate/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpf5hyhjpcpip-wheel- --python-tag cp36:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for tabulate
  Running setup.py clean for tabulate
Failed to build two1 protobuf pyaes pyyaml sha256 tabulate
Installing collected packages: protobuf, pyaes, atomicwrites, py, more-itertools, pluggy, attrs, pytest, pyyaml, sha256, tabulate, two1, pywallet
  Running setup.py install for protobuf ... error
    Complete output from command /home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/protobuf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lxvcezkd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tomtony/python_env/blockchain-env/include/site/python3.6/protobuf:
    running install
    running build
    running build_py
    Generating google/protobuf/descriptor_pb2.py...
    Can't find required file: ../src/google/protobuf/descriptor.proto
    
    ----------------------------------------
Command "/home/tomtony/python_env/blockchain-env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6u5wc1x2/protobuf/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-lxvcezkd-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tomtony/python_env/blockchain-env/include/site/python3.6/protobuf" failed with error code 255 in /tmp/pip-build-6u5wc1x2/protobuf/
(blockchain-env)
```
