### ISSUE TITLE
cannot import name 'encode_hex'

### ISSUE THREAD

**Issue by cevin** [ranaroussi/pywallet#21]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pywallet/wallet.py", line 5, in <module>
    from .utils import (
  File "/usr/local/lib/python3.7/site-packages/pywallet/utils/__init__.py", line 5, in <module>
    from .ethereum import (
  File "/usr/local/lib/python3.7/site-packages/pywallet/utils/ethereum.py", line 28, in <module>
    from rlp.utils import encode_hex
ImportError: cannot import name 'encode_hex' from 'rlp.utils' (/usr/local/lib/python3.7/site-packages/rlp/utils.py)
```

**Comment by ztlovemst11** [comment]
https://github.com/ethereum/pyrlp/issues/96

you can refer to this link
