### ISSUE TITLE
os error

### ISSUE THREAD

**Issue by edinaldofox** [ranaroussi/pywallet#30]
Traceback (most recent call last):
  File "create_eth_wallet.py", line 1, in <module>
    from pywallet import wallet
  File "/usr/local/lib/python2.7/dist-packages/pywallet/wallet.py", line 5, in <module>
    from .utils import (
  File "/usr/local/lib/python2.7/dist-packages/pywallet/utils/__init__.py", line 5, in <module>
    from .ethereum import (
  File "/usr/local/lib/python2.7/dist-packages/pywallet/utils/ethereum.py", line 20, in <module>
    from two1.bitcoin.utils import bytes_to_str
  File "/usr/local/lib/python2.7/dist-packages/two1/bitcoin/__init__.py", line 19, in <module>
    from .block import BlockHeader
  File "/usr/local/lib/python2.7/dist-packages/two1/bitcoin/block.py", line 7, in <module>
    from two1.bitcoin.txn import Transaction
  File "/usr/local/lib/python2.7/dist-packages/two1/bitcoin/txn.py", line 7, in <module>
    from two1.bitcoin import crypto
  File "/usr/local/lib/python2.7/dist-packages/two1/bitcoin/crypto.py", line 18, in <module>
    bitcoin_curve = secp256k1()
  File "/usr/local/lib/python2.7/dist-packages/two1/crypto/ecdsa_openssl.py", line 449, in __init__
    super().__init__(hashlib.sha256)
TypeError: super() takes at least 1 argument (0 given)
Exception AttributeError: "'secp256k1' object has no attribute '_lc'" in <bound method secp256k1.__del__ of <two1.crypto.ecdsa_openssl.secp256k1 object at 0x7fb4ecabd610>> ignored

**Comment by henrytom1703** [comment]
I have a same this issue

**Comment by keviny** [comment]
Meet the same issue, in 2.7

**Comment by fedor-ivn** [comment]
I also have the same issue

**Comment by bloonfield** [comment]
seems not working on Mac
