### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Hole-code** [ranaroussi/pywallet#64]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ozwhp5we/protobuf_234c0cbb441b41ac80bace1540906dd8/setup.py", line 29, in <module>
          from distutils.command.build_py import build_py_2to3 as _build_py
      ImportError: cannot import name 'build_py_2to3' from 'distutils.command.build_py' (/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build_py.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by xfaceS** [comment]
me too same error

**Comment by knkr1** [comment]
Because Pywallet supports the 3.6 version of Python.
I was able to fix the issue by downgrading my Python to 3.6
